
owner: odanado
repo: upptime

sites:
  - name: odan.dev
    url: https://odan.dev
  - name: blog.odan.dev
    url: https://blog.odan.dev

status-website:
  name: Upptime
  baseUrl: /upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
